### PR TITLE
Temporary fix for wayland

### PR DESCRIPTION
**Pull request by rkuklik**
## What kind of change does this PR introduce?
- Fix
- Refactor

## Did this PR introduce a breaking change? 
_--novsync_ currently doesn't work, some dependencies switched their APIs.

Given that glutin 0.30 completely switched its API, some parts would benefit from partial rewrite (currently there is _Context_ struct in _opengl.rs_ providing glue between old and new parts of code that doesn't look very nice).

This change fixes problems over on wayland, but I wasn't able to test other platforms than linux.

### CODE REVIEW

**Comment by tobealive** [comment]
Fixes the keyboard stuck issues on linux x11 for me (related #1192)

The PR might interfere with other ongoing work though.

**Comment by tobealive** [comment]
Some of the recent related works that came to my mind are: #1789 and #1790. The later discusses to move away from winit.

I think it would require to proactively come together to find a good way on how to proceed.

**Comment by DashieTM** [comment]
I tested this out and it works perfectly fine other than some strange things happening with a few keys. 
For example the k key seems to not repeat, but h j and l work fine.
The same thing goes with the arrow keys where right and up work, but down and left are only received once, the repeats are dropped.
Is this perhaps an issue with a certain config? The keys work with xwayland mode, although with lag... and they obviously work in regular nvim.

It is a shame that this wonderful project doesn't work on wayland yet.
It looks and feels amazing, but I just can't justify going back to x11 ever again.

**Comment by DashieTM** [comment]
Seems to be an issue with upstream, there is another fork that tried to integrate newer versions of winit and glutin and the same issue is happening there.

**Comment by Yesterday17** [comment]
> I tested this out and it works perfectly fine other than some strange things happening with a few keys. For example the k key seems to not repeat, but h j and l work fine. The same thing goes with the arrow keys where right and up work, but down and left are only received once, the repeats are dropped. Is this perhaps an issue with a certain config? The keys work with xwayland mode, although with lag... and they obviously work in regular nvim.
> 
> It is a shame that this wonderful project doesn't work on wayland yet. It looks and feels amazing, but I just can't justify going back to x11 ever again.

This seems to be a upstream issue. I left a comment at https://github.com/rust-windowing/winit/commit/639e1d40b13a38d9545e452d9f7e7ae5b77e4740#r108100537.

I tried to fix it by adding `8` as code above. Could you please verify whether the issue still exists on other keys? (I only tried `KeyK`)

**Comment by DashieTM** [comment]
The following keys are also affected: 
left-arrow, down-arrow, up-arrow,m,1,2,3,4,5,6,7
as well as any combination with modifiers -> m and M
It is really weird, as all the other keys work perfectly fine.

**Comment by fredizzimo** [comment]
@rkuklik I cherry-picked your changes into https://github.com/neovide/neovide/pull/1789, but using the upstream glutin-winit instead of embedding it here. It's still unclear to me how we are going to deal with the upstream key repeat bug though.

Could you check that I haven't missed something, and that it still works? And if that's the case, I think we can close this one and start using https://github.com/neovide/neovide/pull/1789 instead.

**Comment by fredizzimo** [comment]
Yes, I will merge @Yesterday17's keyboard repeat fixes. But the other fixes in the PR does not seem to be needed, everything compiles wihtout that.

As for the two version of winit, I also encountered that, but I explictly set the version numbes and used the patch feature of Cargo https://github.com/neovide/neovide/pull/1789/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R96, and ran `cargo update`.

**Comment by fredizzimo** [comment]
The keyboard repeat fix is now included in https://github.com/neovide/neovide/pull/1789

Could someone confirm that everything works there, so we can close this PR?

**Comment by DashieTM** [comment]
I just tested the new-keyboard-v3 branch(#1789), it works! Thank you all for the amazing work!

**Pull request closed without merging**
