### PR TITLE
Fix test function call

### PR DESCRIPTION
**Pull request by last-partizan**
This is small fix, correcting `cargo test` run.

## What kind of change does this PR introduce?
- [x] Fix
- [ ] Feature
- [ ] Codestyle
- [ ] Refactor
- [ ] Other

## Did this PR introduce a breaking change?
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- [ ] Yes, please list breaking changes
- [x] No

### CODE REVIEW

**Comment by Kethku** [comment]
@last-partizan thanks for the fix :)

**Comment by j4qfrost** [comment]
I think one bonus added by the clippy change is that you can add a GitHub token and the clippy changes will be automatically applied @Kethku

**Comment by j4qfrost** [comment]
@last-partizan not complaining but you should've checked the code style box.

**Comment by last-partizan** [comment]
@j4qfrost that's not code style, that was broken test

complaints during pre commit hook was from `cargo test`, not from `cargo fmt` or something

**Comment by j4qfrost** [comment]
You made a change to the clippy actions for the GitHub CI. Was that from another branch?

**Comment by last-partizan** [comment]
@j4qfrost you mean this? https://github.com/Kethku/neovide/pull/781/files

That wasn't me :)

**Pull request merged**
