### PR TITLE
Remove unnecessary clones and allocations from bridge module

### PR DESCRIPTION
**Pull request by luisholanda**
Thanks for writing this awesome project! 

Exploring the code I saw that the `bridge` module make a lot of `.clone`s and owned values when references are enough. This PR fixes what I found.

The commits are very isolated and can be reviewed in isolation.

As a tip, dunno if you knew the tool but [clippy](https://github.com/rust-lang/rust-clippy) pointed many of the issues that this PR fixes.

### CODE REVIEW

**Comment by Kethku** [comment]
Thanks for the PR! This looks great. My only issue is that I am currently in the middle of rewriting the keyboard management, so I can't merge this unless that file's changes are removed. Otherwise I suspect this will improve performance non trivially. I appreciate the help!

**Comment by Kethku** [comment]
Welp I've given up on the keybinding rewrite again. So I might as well merge this.

**Comment by KillTheMule** [comment]
Huh, you're fast. I'll make my comment anyways, maybe you're interested in revisiting:

My recommendation is to take `Value`s by value, and return the owned, decoded value, rather than taking and returning a reference. I don't see a usecase for keeping the old `Value` around, and that way you can elide even more clones (e.g. [this one](https://github.com/Kethku/neovide/pull/81/files#diff-adf795efa9299f343af5f94871dc2b46R213)). It also feels much cleaner to me.

You can use the [`TryFrom`](https://docs.rs/rmpv/0.4.3/rmpv/enum.Value.html#impl-TryFrom%3CValue%3E) implementations for nice error reporting, although for `nvim-rs` I had to resort to [my own variant of the trait](https://github.com/KillTheMule/nvim-rs/blob/master/src/rpc/unpack.rs) because you can't very well implement `TryFrom` recursively because of the ambiguity introduced by msgpack's `Binary` Value.

**Comment by luisholanda** [comment]
Yeah, we could defitely do that. I will see what I can do.

**Pull request merged**
