### PR TITLE
Add window maximization

### PR DESCRIPTION
**Pull request by j4qfrost**
This is a bit of a quick hack. The clean way would involve deglobalizing EDITOR.

### CODE REVIEW

**Comment by Kethku** [comment]
my multigrid branch deglobalizes the bridge, editor, and renderer. It leaves the redraw scheduler and settings as globals since their influence is broad and largely immutable (or at least lockless)

For now this unblocks the user, but I kinda feel like using the same command creation logic that was introduced for the context menu integration work that was merged recently would be a more vim-y way to solve this problem.

What do you think?

**Comment by j4qfrost** [comment]
Yeah, I was going for that approach initially, then I realized just how much I would have to change to make sending the command play nice, I can wait. I need to take a look at your multigrid changes.

**Comment by Kethku** [comment]
I'm actively working on it, its just gonna be a bit

**Comment by Kethku** [comment]
FYI still working on this. I want to at least squash most of the bugs before I merge cause there seems to be a lot of folks running from master

**Comment by j4qfrost** [comment]
I know you don't mean it that way, but I'm sorry lol.

**Comment by Kethku** [comment]
I 100% was not saying that as a poke at you!

**Comment by Kethku** [comment]
superseded by https://github.com/Kethku/neovide/pull/442/files

**Pull request closed without merging**
