### PR TITLE
Multigrid

### PR DESCRIPTION
**Pull request by Kethku**
Work in progress multigrid support. Renders works now which is awesome. There are some remaining bugs and the occasional render issue which is concerning.

Remaining work:
- [x] Setting to enable and disable multigrid extension (this may not be possible at runtime)
- [x] Grid based cursor positioning
- [x] Clip offscreen windows
- [x] Blurred background of floating windows
- [x] Animated grid positioning
- [x] General code cleanliness
- [x] Perf testing
- [x] Windows appear in top left corner before being re-positioned
- [x] No way to disable multigrid support
- [x] Popup windows prevent neovide from responding to ui commands
- [x] No way to disable window animations
- [x] No way to disable or configure window transparency

### CODE REVIEW

**Comment by Kethku** [comment]
This PR is blocked on https://github.com/neovim/neovim/issues/13416

**Comment by Kethku** [comment]
And https://github.com/neovim/neovim/pull/12667

**Comment by Kethku** [comment]
Remaining tasks:
- [ ] Windows appear in top left corner before being re-positioned
- [ ] No way to disable multigrid support
- [ ] Popup windows prevent neovide from responding to ui commands
- [ ] No way to disable window animations
- [ ] No way to disable or configure window transparency

**Comment by Kethku** [comment]
Ok remaining work:
- [ ] Fix tests
- [ ] Port winit windowing system
- [ ] Port other commits since this PR branched off

**Comment by Kethku** [comment]
All done! I think I'm gonna merge this

**Comment by j4qfrost** [comment]
Exciting times.

**Pull request merged**
