### PR TITLE
Add clippy check to CI

### PR DESCRIPTION
**Pull request by smolck**
## What kind of change does this PR introduce?
- [ ] Fix
- [x] Feature <- putting this but I guess it could also be Other or Codestyle . . .
- [ ] Codestyle
- [ ] Refactor
- [ ] Other

## Did this PR introduce a breaking change?
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- [ ] Yes, please list breaking changes
- [x] No

### CODE REVIEW

**Comment by smolck** [comment]
Can see it in action (ha!) here: https://github.com/smolck/neovide/pull/2/files

**Comment by Kethku** [comment]
Should this include removing the equivalent clippy/formatting check changes from the main pipeline?

**Comment by smolck** [comment]
Yep, done.

**Comment by Kethku** [comment]
I don't mean to be difficult haha but would it make sense to move the formatting check as well?

**Comment by smolck** [comment]
Yes, I was just being lazy lol/not super familiar with GH actions, but it should work now.

**Comment by j4qfrost** [comment]
Ideally we should just be allowing CI to just make those formatting changes.

**Pull request merged**
