### PR TITLE
Update rust-skia to support aarch64

### PR DESCRIPTION
**Pull request by shaunsingh**
## What kind of change does this PR introduce?
- [x] Fix
- [ ] Feature
- [ ] Codestyle
- [ ] Refactor
- [ ] Other

## Did this PR introduce a breaking change?
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- [ ] Yes, please list breaking changes
- [x] No

Tested locally on a chromebook machine, seems to work fine. Fixes https://github.com/Kethku/neovide/issues/766. I would just double check with @Shatur before merging 

Side note: I think quite a few of the dependencies are out of date now. Is it possible to add dependabots for rust? if not, I might have to manually take a look at them one day

### CODE REVIEW

**Comment by Kethku** [comment]
I'm inclined to merge this regardless as it probably doesn't break anything.

**Comment by Shatur** [comment]
@Kethku @shaunsingh Can't build this. The error is exactly the same. I guess we should update the version inside the `.toml` file too.

**Comment by shaunsingh** [comment]
@Shatur Whoops, forgot about that. Fixed in https://github.com/Kethku/neovide/blob/main/Cargo.toml, I think it should work now

**Comment by Shatur** [comment]
@shaunsingh @Kethku Now the build is broken for all platforms, you forgot to update the checksums. See #798.

**Pull request merged**
