### PR TITLE
Initial Implementation for #622

### PR DESCRIPTION
**Pull request by bbli**
Hey there!

So I tried to call neovim to get the standard path as suggested by Pangoraw in #622 , but because of the way this code is structured, it causes the following problem:
1. We would need to extract a neovim handle from "start_bridge" and pass it on to "create_window", since both functions call "window_geometry_or_default". That is sort of ugly.
2. If we instead just make the call to neovim just inside "start_bridge" and writing to the SETTINGS global variable, "start_bridge" would need to be synchronized with "create_window". But that's not good as we don't want to block.

So, I just hardcoded the respective paths for unix and windows. If neovim does decide to change what `:call stdpath("data")` evaluates to, we can just change it with a simple commit.

I used serde as @Kethku suggested, but as of now the code assumes the neovide-settings.txt file only contains the last window size, rather than being some sort of general json structure. I think once that is done, we can just read the settings file in main, and pass the json object on to "start_bridge" and "create_window"?(Since right now I reread the file in each of those functions) 

(All changes in the 2 renderer files was because of rustfmt.)
(Also, as an aside, is there a way for me to temporarily turn off CI when making commits? I would like to make a bunch of smaller commits as I work, and then squash when I finally finish.)

### CODE REVIEW

**Comment by Kethku** [comment]
Thanks so much for digging into this! I'm a bit swamped mid week but will try to get to this this weekend to review.

A couple thoughts:
1. you can turn off the cargo checks by using the -n argument when doing git commands. I have removed the hooks in the opengl branch (but if you swap I think you have to manually remove them from the .git folder)
2. current development is targeting the opengl branch. Any chance you could rebase on that and have the PR set to merge to opengl?
3. Given that the solution requires calling a data path in neovim and then accessing that data. I wonder if the correct way to solve this is expose some mechanism for setting and retrieving the size of the window in neovim itself and then writing a plugin to do the save and restore that way. If necessary we could ship that plugin with neovide somehow, but that way the code that is really neovim specific can live in neovim. What do you think?

Regardless, I will take a look at the PR and give some more in depth thoughts soon. Thanks again!

**Comment by bbli** [comment]
Yeah no problem. I wanted to learn more about neovide's internals, and as it turns out, this was indeed a good first issue for doing so!

> you can turn off the cargo checks by using the -n argument when doing git commands. 

k, thanks for the tip.

> Any chance you could rebase on that and have the PR set to merge to opengl?

Alright, I will try to get a working commit in before the weekend so you can review it. 

> expose some mechanism for setting and retrieving the size of the window in neovim itself and then writing a plugin to do the save and restore that way.

Hmm, can neovim do serialization, or do you just want to get `stdpath`? The stdpath is a soft dependency though, as even if neovim decides to change the location(which I think is unlikely), neovide will continue working.

**Comment by bbli** [comment]
Alright, the executable works now on the opengl branch, though some tests are failing from missing a "font_fix" import. Also, just wondering, why is `INITIAL_DIMENSIONS` type (u64,u64), when it just gets converted later to u32 for `PhysicalSize<u32>`/`LogicalSize<u32>`?

**Comment by Kethku** [comment]
I don't think theres a particular rhyme or reason for why we would use u32 vs u64 other than history. Its possible that sdl2 used u64 for window sizes or something similar. As for how to get the data into the right place I'll have to think a bit more. I generally try to send that kind of data via ui commands or similar in order to communicate between the different components, but its become somewhat clunky...

**Comment by bbli** [comment]
> a particular rhyme or reason 
haha, ok. 

> As for how to get the data into the right place I'll have to think a bit more
Yeah, no probs. Let me know when you want to pick this back up!

**Comment by Kethku** [comment]
Looks like when I deleted the opengl branch, this PR got disabled. Not sure why. Maybe this needs to be rebased on main now?

**Comment by bbli** [comment]
Kk, I am a bit busy atm but will get around to it by the end of the week. 

So any updates on what you think the best way is to handle the save location + how to load the persistent setting variables into neovide :)?

**Pull request closed without merging**
