### PR TITLE
refactor(startup): Use SETTINGS to store window geometry

### PR DESCRIPTION
**Pull request by last-partizan**
While i was researching neovim startup sequence, i refactored it a little.

- Removed multiple calls to functions getting window size
- Now there is only one call, when parsing command line arguments
- After this value is used from SETTINGS

I think this way it is better. @Kethku what do you think?

---------------------

## What kind of change does this PR introduce?
- Refactor

## Did this PR introduce a breaking change?
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- No

Btw, i suppose no one objects i'm using just lists instead of checkboxes in this template? Github is treating checkboxes as "tasks", and i don't like having "2 of 7 tasks" on my PRs :)

### CODE REVIEW

**Comment by shaunsingh** [comment]
> Btw, i suppose no one objects i'm using just lists instead of checkboxes in this template? Github is treating checkboxes as "tasks", and i don't like having "2 of 7 tasks" on my PRs :)

Off topic but I'm thinking of reverting that as well. The checkboxes were added a while back but I didn't realize it gets picked up as a task

**Comment by Kethku** [comment]
@last-partizan I think this is a great change. My only suggestion would be to move the geometry related functions into their own file. But its up to you.

**Comment by last-partizan** [comment]
Hmmm.

That's only one "get_window_geometry", and it's only parsing command line argument. But, wait a minute.

I see settings/from_value.rs, and there is parsing options, but for simple types.

Can we do something like `impl FromValue from WindowGeometry`? That would be great. I'll try it!

**Comment by last-partizan** [comment]
Idea was great, but i haven't been able to make it work. Or it's not possible to do it the way i wanted.

Maybe another time.

But i splitter parsing function into separate file and it looks better now.

**Comment by Kethku** [comment]
Looks good to me. Merging.

**Pull request merged**
