### PR TITLE
fix(window_wrapper): Fix unmaximize behaviour

### PR DESCRIPTION
**Pull request by last-partizan**
set_inner_size was using LogicalSize from current physical size,
it was working fine only for scaling=1.
Removing this leaves unmaximizing to winit, which does it correctly.

## What kind of change does this PR introduce?
- [x] Fix
- [ ] Feature
- [ ] Codestyle
- [ ] Refactor
- [ ] Other

## Did this PR introduce a breaking change?
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- [ ] Yes, please list breaking changes
- [x] No

## Before merging this i want to know it doesn't break maximize/unmaximize on other platforms

- [x] Linux (it works fine under Gnome wayland/xwayland)
- [ ] Windows
- [ ] MacOS

### CODE REVIEW

**Comment by Kethku** [comment]
Youre fixing these before I can get to them! Great stuff, this looks great to me.

**Comment by last-partizan** [comment]
Oh, you're merged it too fast :)

I wanted for someone to test it first. For now let's hope it works on other platforms as fine as on linux :)

**Comment by Kethku** [comment]
I'll test it now. I encountered the same issue on windows.

**Comment by Kethku** [comment]
Fix worked for me!

**Comment by vivlim** [comment]
Confirmed this fixed #790 on macos.

**Pull request merged**
