### PR TITLE
rust fmt

### PR DESCRIPTION
**Pull request by j4qfrost**
I didn't read your comment carefully enough about the rebase. I was a bit too stuck in my own head. Here is the fmting.

### CODE REVIEW

**Comment by Kethku** [comment]
Awesome! Thanks so much! Is there anything we can do script wise or configuration wise which would ensure that rustfmt is preserved? I'm thinking maybe a build task that causes PRs to fail if they don't match formatting? If nothing immediate comes to mind I can merge this and figure that out later.

**Comment by j4qfrost** [comment]
I can get to working on that. Is github able to perform status checks internally? If not we can just build it on Travis or some other provider to check whether ```cargo fmt --all -- --check``` passes.

**Comment by prabirshrestha** [comment]
Wezterm has pretty good github actions. Might be port those here?

https://github.com/wez/wezterm/tree/master/.github/workflows

**Comment by Kethku** [comment]
The relevant lines appears to be https://github.com/wez/wezterm/blob/master/.github/workflows/gen_windows.yml#L45-L47

**Comment by Kethku** [comment]
Our github actions setup exists here: https://github.com/Kethku/neovide/blob/master/.github/workflows/build.yml and they get run here: https://github.com/Kethku/neovide/actions

**Comment by Kethku** [comment]
I can handle this soonish, but if you wanna get something up and running that would be great!

**Comment by j4qfrost** [comment]
Sorry, I'm unfamiliar with Github workflows, but it looks like I added the line successfully. I did hit a bit of a confusing snag though:
```Caused by:
  failed to get 200 response from `https://crates.io/api/v1/crates/kernel32-sys/0.2.2/download`, got 502```

Do workflows provide a status check that you can test for the merge requirements?

**Comment by j4qfrost** [comment]
I see it in the branch checks now. Ready to merge!

**Comment by Kethku** [comment]
Thanks!

**Pull request merged**
