### PR TITLE
check font stretch property when selecting

### PR DESCRIPTION
**Pull request by NBonaparte**
Solves an issue I had where it was selecting a font with the correct weight and style but wrong "stretch".

### CODE REVIEW

**Comment by Kethku** [comment]
Very interesting. Do you have any data as to what stretch means?

**Comment by NBonaparte** [comment]
Stretch refers to whether the font is condensed/expanded. In this case, I set the font to Iosevka, but it selected Iosevka Expanded for bold fonts, which caused the bold text to be cut off at the end.

neovide_bold_expanded

**Comment by Kethku** [comment]
Gotcha. This makes perfect sense to me!

**Comment by Kethku** [comment]
Gotcha. This makes perfect sense to me!

**Pull request merged**
