### PR TITLE
Fix --wsl option

### PR DESCRIPTION
**Pull request by calvinkosmatka**
Hi,
This PR addresses the WSL issues mentioned in #50. It works locally, but could probably use some more testing. Let me know what you think of the changes!

Edit: spoke too soon, release build didn't work. Removing `#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]` makes it work for some reason.

### CODE REVIEW

**Comment by calvinkosmatka** [comment]
Ok, `nvim.eval("has(\"nvim-0.4\")").await`  returns an
```rust
Err(DecodeError(InvalidMessage(NotAnArray(Integer(PosInt(84))))))
```
consistently with windows_subsystem =  "windows", causing neovide to exit with the "Neovide requires version 0.4 or higher" message, and a 0 exit code. nvim_rs indicates [here](https://github.com/KillTheMule/nvim-rs/blob/master/src/error.rs#L50) that InvalidMessage errors are indicative of neovim bugs, but I'm not sure if that's the right path to go down here.

**Comment by calvinkosmatka** [comment]
After a bit of research into WSL io redirection issues, I guessed that using inherited Stdio for WSL's stderr was causing the rpc problems when running the release build. I changed it to used piped stderr and it worked perfectly. @Kethku I think this is _actually_ ready for review/further testing now.

A couple specific questions I have:

- Do you think I should move the WSL command building portion into a separate function? Maybe `wsl_build_nvim_cmd`?
- Does how I cfg-gated inherited vs piped stderr seem reasonable (particularly for non-Windows)?

**Comment by Kethku** [comment]
@calvinkosmatka I just merged a big change which changes pretty much every file in the project. It cleans up a bunch of issues and makes the architecture cleaner, but results in open PRs needing to be basically rebuilt on top of it.

**Comment by Kethku** [comment]
I'm happy to port it if you'd like, or you can do it. Up to you :)

**Comment by calvinkosmatka** [comment]
It looks like the parts of bridge/mod.rs that I touch here stayed mostly intact, so I think I'll be able to rebase without too much of an issue. I'll give it a try a little later today!

**Comment by calvinkosmatka** [comment]
@Kethku A little trickier than I thought, but it's working now!

**Comment by Kethku** [comment]
Ok I'll take a look soon. Thanks for the work!

**Comment by Kethku** [comment]
Looks great. Thank you so much!

**Comment by Kethku** [comment]
https://github.com/Kethku/neovide/wiki/Configuration#wsl the documentation for the feature has been added here. I'll elaborate a little in the readme too!

**Comment by keepitsane** [comment]
How would one go about using Node and Python providers from WSL rather then the Windows ones when using the `--wsl` option. I have my providers set to the WSL side path, but when starting Neovide using wsl it seems to default to the providers from the Windows side. Thanks in advance!

**Pull request merged**
