### PR TITLE
Add option to install neovide from snap

### PR DESCRIPTION
**Pull request by brymer-meneses**

### CODE REVIEW

**Comment by j4qfrost** [comment]
I would like to wait until opengl is merged into main before it gets listed as an option on the README. Once it's in main and hopefully after we sort out the mysterious issue involving a missing egl function pointer (though this isn't a dealbreaker), I will move neovide into the stable channel, so we won't have to list it as beta.

**Comment by Kethku** [comment]
@j4qfrost is this ready to merge now?

**Comment by j4qfrost** [comment]
It needs another commit to switch to the stable channel, and a change for the readme. I'll send in a PR in a bit.

**Comment by j4qfrost** [comment]
Closing in favor of this https://github.com/Kethku/neovide/pull/722

**Pull request closed without merging**
