### PR TITLE
Transparent test

### PR DESCRIPTION
**Pull request by axeldetlofsson**
Testing transparent background
Screenshot_20210826_150708

### CODE REVIEW

**Comment by alvinlee001** [comment]
Sorry guys and @axeldetlofsson , i was just wondering why this is not merged. Is it bcz it breaks or not working in some other OSes? I am trying to set my neovide to a transparent bg. Is it possible for me to merge ur changes in my local copy so i could get the transparency shown?

**Comment by Liverm0r** [comment]
@alvinlee001 it seems to be supported `let g:neovide_transparency=0.8`

**Comment by alvinlee001** [comment]
> @alvinlee001 it seems to be supported `let g:neovide_transparency=0.8`, [docs](https://github.com/neovide/neovide/wiki/Configuration#transparency)

Yes @Liverm0r sorry i did not go through the the wiki docs, thanks this neovim editor is the coolest!!

**Comment by iafshinafshin** [comment]
Hello, i can't use your code in my neovim config with _**lua language**_ but i used this code in my neovim  config(**lua**) → `vim.g.neovide_transparency = 0.8`

**Pull request closed without merging**
